# Generated by Django 3.1.5 on 2021-01-15 20:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_id', models.CharField(default=api.models.generate_unique_code, max_length=8, unique=True)),
                ('session', models.CharField(max_length=50)),
                ('label', models.CharField(default='no label', max_length=50)),
                ('seq_type', models.CharField(choices=[('D', 'DNA'), ('R', 'RNA')], default='D', max_length=1)),
                ('sequence', models.CharField(default='', max_length=500)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
