# Generated by Django 3.1.5 on 2021-01-16 02:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq_id',
            field=models.CharField(default=api.models.generate_unique_code, max_length=8),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='seq_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='D', max_length=3),
        ),
    ]
