# Generated by Django 3.1.5 on 2021-01-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210116_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
