# Generated by Django 3.1.5 on 2021-01-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210116_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
