# Generated by Django 3.1.5 on 2021-01-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210116_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='sequence',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
