# Generated by Django 3.1.5 on 2021-01-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210116_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='label',
            field=models.CharField(default='no label', max_length=50, unique=True),
        ),
    ]
