# Generated by Django 3.1.5 on 2021-01-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210119_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='seq_type',
            field=models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=3),
        ),
    ]
