# Generated by Django 3.1.5 on 2021-01-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210119_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='label',
            field=models.CharField(default='no label', max_length=50),
        ),
    ]
